<?php
/**
 * Created by PhpStorm.
 * User: hlh XueSi <1592328848@qq.com>
 * Date: 2023/5/7
 * Time: 6:11 下午
 */
declare(strict_types=1);

namespace EasyApi\Lang\Tests;

use EasyApi\Lang\Lang;
use PHPUnit\Framework\TestCase;

class LangTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $langFilePath = __DIR__ . DIRECTORY_SEPARATOR . 'LangFile';
        $fileList = scandir($langFilePath);
        $lang = Lang::getInstance();
        foreach ($fileList as $file) {
            $range = pathinfo($file, PATHINFO_FILENAME);
            $filePath = $langFilePath . DIRECTORY_SEPARATOR . $file;
            $lang->load($filePath, $range);
        }
    }

    public function testGet()
    {
        $lang = Lang::getInstance();

        $ret = $lang->get('xuesi', [], 'zh-cn');
        $this->assertSame('XueSi', $ret, 'get lang error');

        $ret = $lang->get('xuesi', [], 'en');
        $this->assertSame('Xue.Si', $ret, 'get lang error');

        $vars = [
            'age'  => 18,
            'name' => 'XueSi',
        ];
        $ret = $lang->get('xuesi_age_name', $vars, 'zh-cn');
        $this->assertSame('XueSi是18岁，名字是XueSi', $ret, 'get lang error');
    }

    public function testGetByFunc()
    {
        $ret = lang('xuesi');
        $this->assertSame('XueSi', $ret, 'get lang error');

        $ret = lang('xuesi', 'en');
        $this->assertSame('Xue.Si', $ret, 'get lang error');

        $vars = [
            'age'  => 18,
            'name' => 'XueSi',
        ];
        $ret = lang('xuesi_age_name', 'zh-cn', $vars);
        $this->assertSame('XueSi是18岁，名字是XueSi', $ret, 'get lang error');
    }
}
